name: "Bug Report"
description: "Report an issue found in the application."
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        **Please make sure to fill out all fields to help us resolve the issue faster.**

  - type: textarea
    attributes:
      label: Bug Description
      description: "Provide a clear and detailed description of the bug you encountered."
      placeholder: "Describe the bug..."

  - type: input
    attributes:
      label: Steps to Reproduce
      description: "Provide the steps to reproduce this bug."
      placeholder: "1. Open the app... 2. Click on..."

  - type: input
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
      placeholder: "I expected the app to display..."
  
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: Select the priority level of this issue.
      options:
        - High
        - Medium
        - Low

  - type: input
    attributes:
      label: Additional Information
      description: "Do you have any additional relevant information (logs, screenshots, version, etc.)?"
      placeholder: "Any extra details..."
  