# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, ElementClickInterceptedException
import os
import time


class TestTestFakenodo:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Implicit wait

    def teardown_method(self):
        self.driver.quit()

    def test_testFakenodo(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1854, 1048)
        self.driver.find_element(By.CSS_SELECTOR, ".h2:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Upload dataset").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("Test_Fakenodo")
        self.driver.find_element(By.ID, "desc").click()
        self.driver.find_element(By.ID, "desc").send_keys("Test_Fakenodo")
        self.driver.find_element(By.CSS_SELECTOR, ".content").click()
        self.driver.find_element(By.ID, "publication_type").click()
        dropdown = self.driver.find_element(By.ID, "publication_type")
        dropdown.find_element(By.XPATH, "//option[. = 'Book']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
        self.driver.find_element(By.ID, "tags").click()
        self.driver.find_element(By.ID, "tags").send_keys("FK1,FK2")

        file_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
        file_path = os.path.abspath("app/modules/fakenodo/tests/file10.uvl")
        file_input.send_keys(file_path)

        # Wait for the checkbox to be interactable
        try:
            agree_checkbox = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable((By.ID, "agreeCheckbox"))
            )
            # Scroll the checkbox into view
            self.driver.execute_script("arguments[0].scrollIntoView(true);", agree_checkbox)
            time.sleep(1)
            agree_checkbox.click()
        except TimeoutException:
            print("Timeout waiting for agreeCheckbox to be clickable")
        except ElementClickInterceptedException:
            print("agreeCheckbox is not clickable")

        # Scroll the upload button into view and click it
        upload_button = self.driver.find_element(By.ID, "upload_button")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", upload_button)
        time.sleep(1)
        upload_button.click()
