"""empty message

Revision ID: 4b1382609320
Revises: b86b1d554c2e
Create Date: 2024-12-10 20:13:39.954871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1382609320'
down_revision = 'b86b1d554c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_user', sa.String(length=256), nullable=True)),
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False)),
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github_user'),
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
