# Generated by Selenium IDE
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from core.selenium.common import initialize_driver


class TestFilterbycombination():
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_filterbycombination(self):
        self.driver.get("http://127.0.0.1:5000/")
        time.sleep(1)
        self.driver.set_window_size(1854, 1048)
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Explore").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").send_keys("5")
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys("50")
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.DOWN)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.UP)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.UP)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.DOWN)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").send_keys(Keys.DOWN)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").send_keys(Keys.UP)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_models").send_keys(Keys.UP)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.DOWN)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.UP)
        time.sleep(1)
        self.driver.find_element(By.ID, "number_of_features").send_keys(Keys.UP)
        time.sleep(1)
